language: go
dist: trusty
sudo: false

go:
  - 1.8
  - 1.9
    #  - 1.10

env:
  global:
   - GO15VENDOREXPERIMENT=1
  matrix:
   - TARGET=amd64
   - TARGET=arm64
   - TARGET=arm
   - TARGET=386
   - TARGET=x86
   - TARGET=x64

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
  - go: tip
    env: TARGET=arm
  - go: tip
    env: TARGET=arm64
  - go: tip
    env: TARGET=386

    #before_install:
    # - go get -t -v ./...
    #
    #script:
    # - go test -race -coverprofile=coverage.txt -covermode=atomic
    #
    #after_success:
    # - bash <(curl -s https://codecov.io/bash)
